CREATE DATABASE sistema_bancario;
use sistema_bancario;
create table CLIENTES(
NRO_CLIENTE INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
DNI varchar (15) NOT NULL,
NOMBRE_APELLIDO VARCHAR(60) NOT NULL,
NRO_SUCURSAL INT NOT NULL
#FOREIGN KEY (NRO_SUCURSAL) REFERENCES SUCURSALES(NRO_SUCURSAL)
);

create table CUENTAS(
NRO_CUENTA INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
CBU VARCHAR(50) NOT NULL,
SALDO FLOAT NOT NULL,
NRO_CLIENTE INT NOT NULL,
TIPO_CUENTA CHAR(2) NOT NULL, # CA, CC
TIPO_MONEDA CHAR(1) NOT NULL, # CA, CC
#PRIMARY KEY (CBU),
FOREIGN KEY (NRO_CLIENTE) REFERENCES CLIENTES(NRO_CLIENTE)
);

create table SUCURSALES(
NRO_SUCURSAL INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NOMBRE_SUCURSAL VARCHAR (60) NOT NULL
);
#agrego relacion de cliente con sucursal
alter table clientes add FOREIGN KEY (NRO_SUCURSAL) REFERENCES SUCURSALES(NRO_SUCURSAL);
#agrego una sucursal base
INSERT INTO `sistema_bancario`.`sucursales` (`NOMBRE_SUCURSAL`) VALUES ('Centro');